Projects-main/ecommerceproject/cart/urls.py
from . import views
from django.urls import path
app_name = 'cart_app'

urlpatterns=[
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

Projects-main/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search_app/', include('search_app.urls')),
    path('cart_app/', include('cart.urls')),
    path('',include('shop_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Projects-main/ecommerceproject/search_app/urls.py
from . import views
from django.urls import path
app_name = 'search_app'

urlpatterns=[
    path('',views.SearchResult, name="SearchResult"),
]

Projects-main/ecommerceproject/shop_app/urls.py
from . import views
from django.urls import path

#name_space
app_name = 'shop'

urlpatterns =[
    path('', views.allprodCat, name="allprodCat"),
    path('<slug:c_slug>/', views.allprodCat, name="allprodCat"),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail, name='prodCatdetail'),
]

Projects-main/ecommerceproject/cart/models.py
from django.db import models
from shop_app.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']


    def __str__(self):
        return {}.format(self.cart_id)



class CartIterm(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = "CartIterm"


    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return {}.format(self.product)

Projects-main/ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

Projects-main/ecommerceproject/shop_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_url(self):
        return reverse('shop:allprodCat', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)




class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering =('name',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def get_url(self):
        return reverse('shop:prodCatdetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

Projects-main/ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop_app.models import Product
from .models import Cart, CartIterm
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)

    try:
        cart= Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart= Cart.objects.create(cart_id=_cart_id(request))

    cart.save();

    try:
        cart_item= CartIterm.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except:
        cart_item = CartIterm.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save();

    return redirect('cart_app:cart_detail')

def cart_detail(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartIterm.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return  render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartIterm.objects.get(product=product, cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart_app:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartIterm.objects.get(product=product, cart=cart)

    cart_item.delete()
    return  redirect('cart_app:cart_detail')

Projects-main/ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop_app.models import Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))

    return render(request, 'search.html', {'query': query, 'products': products})

Projects-main/ecommerceproject/shop_app/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
# Create your views here.

def allprodCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404( Category, slug =c_slug)
        products_list = Product.objects.all().filter(category =c_page, available = True)
    else:
        products_list= Product.objects.all().filter(available = True)

    paginator =Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1

    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category':c_page, 'products': products})



def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product':product})

Projects-main/ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">


    <! font aswesome cdn link----------------------->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

<div class="container">
    {% include 'header.html' %}

    {% include 'navbar.html' %}

    {% block body %}

    {% endblock %}



    {% block content %}

    {% endblock %}

    {% include 'footer.html' %}

     <! js---------------------------------------------------------------------------->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</div>
</body>
</html>

Projects-main/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  <h4>This the cart page. Proceed to review your items and place the order</h4>
{% endblock %}


{% block title %}
  <h4>Cart -Ecommerce ABc company PVT LTD</h4>
{% endblock %}


{% block content %}
  {% if not cart_items %}
  <div>
    <div>
      <br>
      <h1 class="text-center my_title">
        Your shopping cart is empty
      </h1>
      <br>
      <p class="text-center">Plase click<a href="{% url 'shop:allprodCat' %}">Here</a> to continue shopping. </p>
    </div>
  </div>

  {% else %}

  <div>
    <div>
      <br>
      <h1 class="text-center my_title">
        Your Shopping cart
      </h1>
    </div>
  </div>

  <div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_custom table">
        <thead class="my_custom_thead">
        <tr>
          <th colspan="5">Your Item</th>
        </tr>
        </thead>

        <tbody>
          {% for cart_item in cart_items %}
            <tr>
              <td>
                <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width : 100px; height: 100px;" class="float-left rounded custom_image"> </a>
              </td>
              <td class="text-left">
                {{cart_item.product.name}}
                <br>
                SKU:{{cart_item.product.id}}
                <br>
                price:${{cart_item.product.price}}
                <br>
                Qty:{{cart_item.quantity}} X $ {{cart_item.product.name}}
              </td>
              <td>
                ${{cart_item.sub_total}}
              </td>
              {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                  <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a><br>
                  &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom-icon"></i></a><br>
                  &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom-icon"></i></a><br>
                </td>
              {% else %}
                <td>
                  &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom-icon"></i></a>
                  &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom-icon"></i></a>
                </td>
              {% endif %}
            </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
          <th>Checkout</th>
        </tr>

        </thead>

        <tbody>
        <tr>
          <td>
            please review your shopping cart items before proceeding with the other payment.
          </td>
        </tr>
        <tr>
          <td><strong class="text-left">Your Total is : {{total}}</strong></td>
        </tr>
        </tbody>
      </table>
      <div class="mx-auto">
        <a href="{% url 'shop:allprodCat' %}" class="btn btn-secondary btn-block my_custom_button">continue shopping</a>
      </div>
    </div>
  {% endif %}
  </div>



{% endblock %}

Projects-main/ecommerceproject/templates/category.html
{% extends 'base.html' %}

{% load static %}

<! meta description -------------------------------------------->
{% block metadescription %}

    {% if category %}
        {{category.description | truncatewords:155}}
    {% else %}
        <h5>Welcome to Ecommerce ABc store where you can buys differeng items.....</h5>
    {% endif %}

{% endblock %}

<! header of website---------------------------------------------->

{% block title %}
    {% if category %}
        <h5>{{category.name}}- Ecommerce ABc store</h5>
    {% else %}
        <h5>see our New collections - Ecommerce ABc store</h5>
    {% endif %}

{% endblock %}

<! block body or content-------------------------------------------->

{% block content %}
    {% if category %}
        <div>
            <div class="row my-row-class">
                <div class="mx-auto">
                    <p><a href="{% url 'shop:allprodCat' %}">Our Product Collection</a></p>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="mx-auto">
        {% if category %}
            <img class="my_image my_image_padding" src="{{category.image.url}}" alt="{{category.name}}">
    </div>

    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text_justify">{{category.descripation}}</p>
    </div>

        {% else %}
            <div class="container fluid">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{% static 'img/banner.png' %}" alt="our product" width="1400px" height="300px">
                    </div>
                </div>
            </div>
            <br>

            <div>
                <h1 class="text-center my_title">our products collections</h1>
                <p class="text_justify">Ecommerce is a method of buying and selling goods and services online. The definition of ecommerce business can also include tactics like affiliate marketing.</p>
            </div>

        {% endif %}

<! product display------------------------------------------------->
    <div class="container">
        <div class="row mx-auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width: 18rem; margin-bottom: 20px;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image"  src="{{product.image.url}}" alt="{{product.name}}" style="height : 300px;"></a>

                    <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                    </div>
                    </div>
                </div>
            {% endfor %}

            <div class="mx-auto" style="margin-bottom : 60px;">
                <h1>Onine Ecommerce ABc</h1>
                {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
                </hr>
                {% endif %}
                <br>
            </div>
        </div>
    </div>

{% endblock %}

Projects-main/ecommerceproject/templates/default.html
{% if item_count < 0 %}

{% endif %}

{% if products.paginator.num_pages < 5 %}

Projects-main/ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p>&copy; Ecommerce ABc tech pvt itd. All rights Reserved</p>
</div>

Projects-main/ecommerceproject/templates/header.html
{% load static %}

<header>
    <center>
        <a href="{% url 'shop:allprodCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage" width="130px" height="130px"></a>
    </center>
</header>

Projects-main/ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Online shopping</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu {% if 'shop' in rquest.path%} activate {% endif %}">
          <a class="dropdown-item" href="{% url 'shop:allprodCat' %}">All product</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
      </li>



        {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-shopping">({{item_count}})</i></a>
          </li>
        {% endif %}

    <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="GET">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success" type="submit"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
    </form>
      </ul>
  </div>
</nav>

Projects-main/ecommerceproject/templates/product.html
{% extends 'base.html' %}

    {% load static %}

<! metadescriptions------------------------------------------->

    {% block metadescription %}
        {{product.description | truncatewords:155}}
    {% endblock %}

<! title------------------------------------------------------->

    {% block title %}
        {% if category %}
            <h4>{{product.name}}- Ecommerce ABc store</h4>
        {% endif %}
    {% endblock %}

<! content--------------------------------------------------------->

    {% block content %}
        <div class="row my_prod_row_class">
            <div class="mx_auto">
                <p><a href="{% url 'shop:allprodCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
            </div>


            <div class="container">
                <br>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-md-12 col-lg-6 text-center">
                        <div class="min-width:18rem">
                            <img src="{{product.image.url}}" alt="{{product.name}}">
                        </div>
                    </div>


                    <div class="col-md-12 col-sm-12 col-md-12 col-lg-6">
                        <div>
                            <h1 class="my_prod_tittle">{{product.name}}</h1>
                            <p>${{product.price}}</p>
                            <p class="my_title">product Description</p>
                            <p class="text-justify my_rod_text">{{product.description}}</p>

                            {% if product.stock <= 0 %}
                                <p class="text-justify my_prod_text"><b>out of stock</b></p>
                            {% else %}
                                <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}">Add to Card</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

Projects-main/ecommerceproject/templates/search.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    <h4>We have variety of products.</h4>
{% endblock %}

{% block title %}
    <h5>Search</h5>
{% endblock %}


{% block content %}
    <div>
        <p class="text-center my_search_text">You have searched for <b>{{query}}</b></p>
    </div>

    <div class="container">
        <div class="row mx-auto">
            {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width: 18rem; margin-bottom: 20px;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image"  src="{{product.image.url}}" alt="{{product.name}}" style="height : 300px;"></a>

                        <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
            <div>
                <p class="text-center my_search_text">0 result Found</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}