Projects-main/Movie_Final/Movie_Final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("search_app/", include('search_app.urls')),
    path('', include('Movie_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projects-main/Movie_Final/Movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'

urlpatterns=[
    path('',views.home,name='home'),
    path('add/', views.add_movie, name='add_movie'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('home_second/', views.home_second, name='home_second'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('review_movie/<int:id>', views.review_movie, name='review_movie'),
    path('display_review/<int:id>/', views.display_review, name='display_review'),
    path('movie_categroy/<int:id>/', views.movie_categroy, name='movie_categroy'),
]

Projects-main/Movie_Final/search_app/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('search_user/', views.search_user, name='search_user')
]

Projects-main/Movie_Final/templates/Login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<! message printing ------------------------------------------>
    {% for msg in messages %}
        <h2 style="text-align : center; color : red;">{{msg}}</h2>
    {% endfor %}

<! Login code -------------------------------------------------->

    <h1 style="text-align : center;">Enter Username and Password</h1>

    <div class="form_add">
        <form method="POST" action="{% url 'movieapp:login' %}">
            {% csrf_token %}
            <label>Useranme</label>
            <input type="text" name="l_name" placeholder="Enter User name"><br>

            <label>Password</label>
            <input type="password" name="l_password" placeholder="Password"><br><br>

            <input type="submit" >

        </form>
    </div>


{% endblock %}

Projects-main/Movie_Final/templates/Navbar.html
{% load static %}

<div class="container">
  <div class="row">
    <div class="col-md-12" style="margin-bottom : 25px; margin-top : 25px;">
      <nav class="navbar navbar-light bg-light justify-content-between">
        <a class="navbar-brand">Movie Zone</a>

        <! dropdown list----------------------------------------------------------------->
        <div class="nav-item dropdown">
        <a class="btn btn-primary" href="#" role="button" data-toggle="dropdown" aria-expanded="false">Categroy ▽</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'movieapp:home' %}">All Movies</a>
          <a class="dropdown-item" href="{% url 'movieapp:movie_categroy' 1 %}">Drama</a>
          <a class="dropdown-item" href="{% url 'movieapp:movie_categroy' 2 %}">Action</a>
          <a class="dropdown-item" href="{% url 'movieapp:movie_categroy' 3 %}">Horror</a>
          <a class="dropdown-item" href="{% url 'movieapp:movie_categroy' 4 %}">Science Fiction</a>
        </div>
      </div>

        <! Register, Login, Home, User Zone----------------------------------------------------->

        <a style="text-align : right;" href="{% url 'movieapp:home' %}" class="btn btn-primary">Home</a>
        <a style="text-align : right;" href="{% url 'movieapp:register' %}" class="btn btn-success">Register</a>
        <a style="text-align : right;" href="{% url 'movieapp:login' %}" class="btn btn-success">Login</a>



        <form class="form-inline" method="GET" action="{% url 'searchapp:search' %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        {% if request.user.is_authenticated %}
        <a  style="text-align : right;" href="{% url 'movieapp:home_second' %}" class="btn btn-primary">welcome - {{user.username}}</a>
        {% endif %}
      </nav>
    </div>
  </div>
</div>

Projects-main/Movie_Final/templates/Navbar_second.html
<div class="container">
  <div class="row">
    <div class="col-md-12" style="margin-bottom : 25px; margin-top : 25px;">
      <nav class="navbar navbar-light bg-light justify-content-between">
        <a class="navbar-brand">User Zone</a>
        <a style="text-align : right;" href="{% url 'movieapp:home' %}" class="btn btn-primary">Movie Zone</a>
        <a style="text-align : right;" href="{% url 'movieapp:add_movie' %}" class="btn btn-primary">Create Post+</a>
        <a  style="text-align : right;" href="{% url 'movieapp:home_second' %}" class="btn btn-primary">User Home</a>
        <a  style="text-align : right;" href="{% url 'movieapp:logout' %}" class="btn btn-danger">logout</a>

        <form class="form-inline" method="GET" action="{% url 'searchapp:search_user' %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </nav>
    </div>
  </div>
</div>

Projects-main/Movie_Final/templates/add.html
{% extends 'base_second.html' %}

{% load static %}

{%
{% block content %}


    <h1 style="text-align : center;">Enter Movie Detail</h1>

    <div class="form_add">
        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}

            <label>Movie title</label>
            <input type="text" name="name" placeholder="Movie Tilte" required><br>

            <label>Description</label>
            <input type="text" name="desc" placeholder="Enter Movie description" required><br>

            <label>Release Date</label>
            <input type="date" name="release_date" placeholder="Enter movie release date" required><br>

            <label>Actor name</label>
            <input type="text" name="actor" placeholder="Enter actors" required><br>

            <label>Categroy</label>
            <select name="categroy" required>
                <option value="1">Drama</option>
                <option value="2">Action</option>
                <option value="3">Horror</option>
                <option value="4">Science Fiction</option>
            </select><br>

            <label>Youtube Trailer link</label>
            <input type="url" name="youtube" placeholder="Enter youtube trailer" required><br>

            <label>Poster</label>
            <input type="file" name="poster" required><br><br>

            <input type="submit" >

        </form>
    </div>

{% endblock %}

Projects-main/Movie_Final/templates/base_second.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Css/style.css' %}">
    <title>Base</title>
</head>
<body style="background-color : aqua;">

{% include 'Navbar_second.html' %}

{% block content %}

{% endblock %}


     <! js---------------------------------------------------------------------------->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

</body>
</html>

Projects-main/Movie_Final/templates/delete.html
{% extends 'base_second.html' %}

{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h2 style="color : red;">Do you want to delete this movie</h2>
        <input type="submit" class="btn btn-success">
    </form>
</div>

{% endblock %}

Projects-main/Movie_Final/templates/display_review.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<! code to display movies name as card---------------------------------------------->


    <div class="container">
        {% for i in Movie_list_review %}
        <div class="cotainer" style="margin-top :10px; margin-bottom : 10px;">
            <h4>Review: </h4><h5>{{i.content}}</h5> <br>
            <h4>Rating: </h4><h5>{{i.rating}}</h5><br>
            <h5>-------------------------------------------------</h5>
        </div>
        {% endfor %}
    </div>

{% endblock %}

Projects-main/Movie_Final/templates/edit.html
{% extends 'base_second.html' %}

{% block content %}

<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
  </form>
</div>

{% endblock %}

Projects-main/Movie_Final/templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<! code to display movies name as card---------------------------------------------->


    <div class="container">
        <div class="row">
            {% for i in Movie_list %}
            <div class="col-md-4">
                <div class="card" style="margin-top: 25px; margin-bottom: 20px;">
                    <img class="card-img-top" src="{{i.poster.url}}" alt="Card image cap" height="250">
                    <div class="card-body" style="align-item : stretch;">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text" style="height : 150px">{{i.desc}}</p>
                    <p class="card-text" style="height : 50px">{{i.actors}}</p>
                    <p class="card-text">{{i.release_date}}</p>
                    <a href="{{i.youtube_link}}" class="btn btn-primary">Trailer</a>
                    <a href="{% url 'movieapp:display_review' i.id %}" style="margin-left : 10px;" class="btn btn-info">View Reviews</a><br>
                    <a href="{% url 'movieapp:review_movie' i.id %}" style="margin-top : 10px;" class="btn btn-secondary">Post Reviews and Ratings</a>


                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

Projects-main/Movie_Final/templates/home_second.html
{% extends 'base_second.html' %}

{% load static %}
{% block content %}

<! code to display movies name as card---------------------------------------------->


    <div class="container">
        <div class="row">
            {% for i in Movie_list_user %}
            <div class="col-md-4">
                <div class="card" style="margin-top: 25px; margin-bottom: 20px;">
                    <img class="card-img-top" src="{{i.poster.url}}" alt="Card image cap" height="250">
                    <div class="card-body" style="align-item : stretch;">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text" style="height : 150px">{{i.desc}}</p>
                    <p class="card-text" style="height : 50px">{{i.actors}}</p>
                    <p class="card-text">{{i.release_date}}</p>
                    <a href="{{i.youtube_link}}" class="btn btn-primary">Trailer</a>
                    <a href="{% url 'movieapp:display_review' i.id %}" style="margin-left : 10px;" class="btn btn-info">View Reviews</a><br>
                    <a class="btn btn-warning" style="margin-top : 10px;" href="{% url 'movieapp:update' i.id %}">Update</a>
                     <a class="btn btn-danger" style="margin-top : 10px;" href="{% url 'movieapp:delete' i.id %}">Delete</a><br>
                    <a href="{% url 'movieapp:review_movie' i.id %}" style="margin-top : 10px;" class="btn btn-secondary">Post Reviews and Ratings</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

Projects-main/Movie_Final/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


    <h1 style="text-align : center;">New Registeration</h1>

    <div class="form_add">
        <form method="POST" action="{% url 'movieapp:register' %}">
            {% csrf_token %}

          <label>Useranme</label>
            <input type="text" name="name" placeholder="Enter User name" required><br>

          <label>First Name</label>
          <input type="text" name="first_name" placeholder="Enter first name" required><br>

          <label>Last Name</label>
          <input type="text" name="last_name" placeholder="Enter first name" required><br>

          <label>Email</label>
          <input type="email" name="email" placeholder="Enter Email" required><br>

          <label>Password</label>
          <input type="password" name="password" placeholder="Password" required><br>

          <label>Confirm Password</label>
          <input type="password" name="c_password" placeholder="Confirm-password"><br><br>

          <input type="submit" >

        </form>
    </div>


{% for msg in messages %}
    <h2 style="text-align : center;">{{msg}}</h2>
{% endfor %}

{% endblock %}

Projects-main/Movie_Final/templates/review.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

    <h1 style="text-align : center;">Enter Movie Review and Rating</h1>

    <div class="form_add">
        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}

            <label>Review</label>
            <input type="text" name="review" placeholder="Enter Movie's review" required maxlength="550"><br><br>

            <label>Rating</label>
            <input type="number" name="rating" min="0" max="10"  step="1.0" required><br><br>

            <input type="submit" >
        </form>
    </div>

{% endblock %}

Projects-main/Movie_Final/templates/search.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div>
        <p class="text-center my_search_text">You have searched for <b>{{query}}</b></p>
    </div>

    <div class="container">
        <div class="row">
            {% for i in movies %}
                <div class="col-md-4">
                    <div class="card" style="margin-top: 25px; margin-bottom: 20px;">
                        <img class="card-img-top" src="{{i.poster.url}}" alt="Card image cap" height="250">
                        <div class="card-body" style="align-item : stretch;">
                            <h5 class="card-title">{{i.name}}</h5>
                            <p class="card-text" style="height : 150px">{{i.desc}}</p>
                            <p class="card-text" style="height : 50px">{{i.actors}}</p>
                            <p class="card-text">{{i.release_date}}</p>
                            <a href="{{i.youtube_link}}" class="btn btn-primary">Trailer</a>
                            <a href="{% url 'movieapp:display_review' i.id %}" style="margin-left : 10px;" class="btn btn-info">View Reviews</a><br>
                            <a href="{% url 'movieapp:review_movie' i.id %}" style="margin-top : 10px;" class="btn btn-secondary">Post Reviews and Ratings</a>
                        </div>
                    </div>
                </div>

            {% empty %}
            <div>
                <p class="text-center my_search_text">0 result Found</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Projects-main/Movie_Final/templates/search_second.html
{% extends 'base_second.html' %}

{% load static %}

{% block content %}
    <div>
        <p class="text-center my_search_text">You have searched for <b>{{query}}</b></p>
    </div>

    <div class="container">
        <div class="row">
            {% for i in movies %}
                <div class="col-md-4">
                    <div class="card" style="margin-top: 25px; margin-bottom: 20px;">
                        <img class="card-img-top" src="{{i.poster.url}}" alt="Card image cap" height="250">
                        <div class="card-body" style="align-item : stretch;">
                            <h5 class="card-title">{{i.name}}</h5>
                            <p class="card-text" style="height : 150px">{{i.desc}}</p>
                            <p class="card-text" style="height : 50px">{{i.actors}}</p>
                            <p class="card-text">{{i.release_date}}</p>
                            <a href="{{i.youtube_link}}" class="btn btn-primary">Trailer</a><br>
                            <a class="btn btn-warning" style="margin-top : 10px;" href="{% url 'movieapp:update' i.id %}">Update</a>
                            <a class="btn btn-danger" style="margin-top : 10px;" href="{% url 'movieapp:delete' i.id %}">Delete</a>
                        </div>
                    </div>
                </div>

            {% empty %}
            <div>
                <p class="text-center my_search_text">0 result Found</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}